apiVersion: apps/v1
kind: Deployment
metadata:
  name: oemiga
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oemiga
  template:
    metadata:
      labels:
        app: oemiga
    spec:
      containers:
      - image: okteto.dev/oemiga:latest
        name: oemiga
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: ParameterSSENCYPT
          value: "chacha20-ietf-poly1305"
        - name: AUUID
          value: "c56fa77c-64a3-4c81-8780-9531856fbd1a"
